### PR TITLE
move ipld to its own repo

### PR DESCRIPTION
**Pull request by dignifiedquire**
The new repo is https://github.com/ipld/specs

Ref #128

### CODE REVIEW

**Comment by nicola** [comment]
In order to avoid 404 to previous links, we should just leave an empty readme with a link to the new spec?

**Comment by dignifiedquire** [comment]
okay

**Comment by dignifiedquire** [comment]
Done

**Comment by dignifiedquire** [comment]
@nicola @jbenet can we merge this?

**Comment by nicola** [comment]
LGTM

**Pull request merged**
