### PR TITLE
Copyediting of the libp2p spec

### PR DESCRIPTION
**Pull request by JesseWeinstein**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Who originally wrote this? Because they should review, this is great feedback on English writing. 

Also, @JesseWeinstein, can you collapse these commits?

**Comment by lgierth** [comment]
cc @diasdavid

**Comment by JesseWeinstein** [comment]
I'm glad to combine these commits into fewer -- would you like just one commit, or?

**Comment by JesseWeinstein** [comment]
OK, I've now squashed all the commits into one. Note that there are a few places where I did a bit of rewording, which needs to be reviewed to make sure I got the meaning correct.

**Comment by RichardLitt** [comment]
Thanks. @diasdavid This is gtg, but you should read it if you like!

**Comment by diasdavid** [comment]
Thank you @JesseWeinstein ! Really appreciate the edits. Hope that that reading spec was helpful :)

**Comment by JesseWeinstein** [comment]
It was, thank you!

**Pull request merged**
