### PR TITLE
Reframe: specify HTTP response status codes

### PR DESCRIPTION
**Pull request by guseggert**

### CODE REVIEW

**Review by willscott — APPROVED** [review]
should we specify semantics of 4xx vs 5xx responses?
e.g. 4xx on client errors (malformed request / etc) and 5xx on server errors

**Comment by guseggert** [comment]
How about I say something like "Non-200 status codes SHOULD follow best practices, e.g. 4xx on client errors, 5xx on server errors, etc.".

**Comment by willscott** [comment]
yeah, or it's fine as is. i think the implicit conventions of HTTP basically work for us here.

**Comment by guseggert** [comment]
(Side note: @lidel is out this week so I am merging this without approval.)

**Pull request merged**
