### PR TITLE
IPIP-309: IPNS Lagrange Replication

### PR DESCRIPTION
**Pull request by Winterhuman**
An IPIP proposal based on https://github.com/ipfs/specs/issues/268.

### CODE REVIEW

**Comment by Winterhuman** [comment]
@aschmahmann Pinging for review

**Comment by BigLep** [comment]
@Winterhuman : apologies for the delay here.  We've been short staffed on the core maintainer / knowledge expert front for this area.  We're also clearly have gaps on making sure IPIP creators have visibility into where their issue is in the queue.  I haven't looked at it yet, but I hope proposals in https://github.com/ipfs/specs/pull/324 about improving the IPIP process move us in a better direction.

At this point, I don't have a commitment on when this will get engagement.

By chance will you be coming to https://ipfs.camp?  That could be a good time to drive a topic like this forward.

**Comment by Winterhuman** [comment]
@BigLep No problem, I understand things have been busy lately. I won't be attending IPFS camp

**Comment by guseggert** [comment]
I am converting this to a draft since there's no working code yet to demonstrate the idea.

**Comment by Winterhuman** [comment]
Closing this pull request while I put it into it's own branch, I'll link the new pull here

**Pull request closed without merging**
