### PR TITLE
Bitswap spec update

### PR DESCRIPTION
**Pull request by dgrisham**
Editing and updating the Bitswap spec. Work in progress. Starts from https://github.com/ipfs/specs/pull/168

### CODE REVIEW

**Comment by dgrisham** [comment]
@diasdavid This is ready for a first-pass review :)

**Comment by diasdavid** [comment]
Skimmed through it, so far so good :)

**Comment by diasdavid** [comment]
@dgrisham when will the final version be ready?

**Comment by dgrisham** [comment]
I'll work on getting the Bitswap sessions section together within the next week or so when I have time. That and the API are the most substantial parts left -- is the API far enough along to be set, or should that be left unfinished for now in lieu of future changes?

**Comment by diasdavid** [comment]
sounds good @dgrisham. Let's take it as it is and continue from there.

**Pull request merged**
